[build]
  base = "/"
  command = "npm install && npm run docs:build"
  publish = "docs/.vitepress/dist"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 